# Generated by Django 3.2.6 on 2021-08-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=15, unique=True)),
                ('original_name', models.URLField()),
                ('created', models.DateTimeField()),
                ('count_open', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
