# Generated by Django 3.2.6 on 2021-08-15 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_alter_url_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_name',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
